GithubIssues/urls.py
from django.conf.urls import url
from . import views

app_name = "RadiusAgent"
urlpatterns = [
url(r'^$', views.home, name='main'),
url(r'^Results/$', views.results, name='results'),
    ]

RadiusAgent/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from GithubIssues import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^FindGitHubIssues/', include('GithubIssues.urls')),
]

GithubIssues/models.py
from django.db import models

# Create your models here.

GithubIssues/views.py
from django.shortcuts import render
import urllib.request as url
import requests
from django.contrib import messages
import math
from .utils import Validations, Data


def home(request):
    # **********************************function description**************************************#
    # Github repositorty url will come in POST function of request                                #
    # First we will validate the url in getUrlParams function of Validations.py file              #
    # If the url is valid we find the required issues count from github API                     #
    # getIssueCount function of Search.py file returns number of issues in last n number of days  #
    # ******************************************************************************************#

    # check if request coming from template is a post request or not
    if request.method == "POST":
        # get github github url entered by user from request
        lv_link = request.POST["GithubLink"]

        # validate if the url is a github repository url
        lo_url = Validations.getUrlParams(lv_link)

        # create full url from api and url entered
        # different componets of query in url
        lv_api_main = "https://api.github.com/search/issues?q=repo:" + lo_url['ev_rep_path'] + "+is:open+type:issue"
        lv_api_pagination = "&page=1&per_page=1"
        lv_api_created_tag = "+created:>"

        # if the url is not a github repository url Validations.getUrlParams returns error message number
        if lo_url['ev_errorNumber'] != 0:
            # errorMessages function of Data.py file returns mressage corresponding to message number
            messages.error(request, Data.errorMessages(lo_url['ev_errorNumber']))
        else:
            # call github api from requests.get() function -->
            lo_issues_data = requests.get(lv_api_main + lv_api_pagination)
            if lo_issues_data.status_code == 403:
                messages.error(request,"Maximum requests within 1 hour to Github API reached. Please try after 1 hour. MORE DETAILES: https://developer.github.com/v3/#rate-limiting")
            elif lo_issues_data.status_code == 422:
                messages.error(request, "Please enter valid github repository link")
            else:
                # convert it into json -->get "total_count" value from json
                lv_total_issue_count = lo_issues_data.json()["total_count"]
                lv_last_24hrs_issues = requests.get(lv_api_main + lv_api_created_tag + Data.getOldTimeStamp(1) + lv_api_pagination).json()["total_count"]

                # subtracting number of issues occured in last 24 hours from no. of issues in last 7 days
                lv_last_24hrs_to_7days_issues = requests.get(lv_api_main + lv_api_created_tag + Data.getOldTimeStamp(7) + lv_api_pagination).json()["total_count"] - lv_last_24hrs_issues

                # # getting remaining issues
                lv_remaining_issues = lv_total_issue_count - lv_last_24hrs_to_7days_issues - lv_last_24hrs_issues

                # returning required parameters in context to template
                context = {
                    "ev_total_issues": lv_total_issue_count,
                    "ev_last_24hrs_issues": lv_last_24hrs_issues,
                    "ev_last_24hrs_to_7days_issues": lv_last_24hrs_to_7days_issues,
                    "ev_remaining_issues": lv_remaining_issues
                }
                return render(request, 'GitHub/ResultPage.html', context)

    return render(request, 'GitHub/HomePage.html')


def results(request):
    return render(request, 'GitHub/ResultPage.html')

GithubIssues/templates/GitHub/HomePage.html
<style>
    body{
        background : ThreeDFace ;
    }
    .post-form{
        position:fixed;
        top:25%;
        left:20%;
        width:100%;
    }
    .submit {
        width: 10%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
    h1{
        position:fixed;
        top:10%;
        left:25%;
        width:50%;
        font-family: "Arial Black", Gadget, sans-serif;
    }
    .input{
        width: 50%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>
<body>
<h1 align="center">Analyse Github Issues</h1>
<form method="POST" align="centre" class="post-form">{% csrf_token %}
         <input name = "GithubLink" class="input" type = url placeholder="Enter your github repository url here"/>
         <button type="submit" class="submit" >Search</button>
        {% for message in messages %}
            <div style="color: darkred">
                *ERROR: {{ message|safe }}
            </div>
        {% endfor %}
    </form>
</body>

GithubIssues/templates/GitHub/ResultPage.html

<style>
    h1{
        position:fixed;
        top:10%;
        left:25%;
        width:50%;
        font-family: "Arial Black", Gadget, sans-serif;
    }
    body{
        background : ThreeDFace ;
    }
.table td {
    font-size: 20px;
    text-align: left;
    color: darkslategray;
    font-family: "Arial Black", Gadget, sans-serif;
}
.table tr {
     color: white;
    cursor: pointer;
}
.table th{
    font-size: 17px;
    text-transform: uppercase;
    text-align: left;
}
    .table{
        position:fixed;
        top:25%;
        left:10%;
        width:75%;
    }
    .button {
        width: 20%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        position:fixed;
        top:45%;
        left:40%;
    }
    h1{
        position:fixed;
        top:10%;
        left:25%;
        width:50%;
    }
</style>
<body>
    <h1 align="center">Github Issues Analysis</h1>
    <div class="results">
        <table class="table" align="center">
            <tr>
              <td>Total number of open issues </td>
              <td>{{ ev_total_issues }}</td>
            </tr>
            <tr>
              <td>Number of open issues that were opened in the last 24 hours </td>
              <td>{{ ev_last_24hrs_issues }}</td>
            </tr>
            <tr>
              <td>Number of open issues that were opened more than 24 hours ago but less than 7 days ago </td>
              <td>{{ ev_last_24hrs_to_7days_issues }}</td>
            </tr>
              <tr>
              <td>Number of open issues that were opened more than 7 days ago </td>
              <td>{{ ev_remaining_issues }}</td>
            </tr>
        </table>
    </div>
    <div>
<button class="button" onclick="window.location.href={% url 'RadiusAgent:main' %}" >Search Again</button>
</div>
</body>
{#{% endif %}#}